import { PrismaClient } from '@prisma/client';
import { AppError } from '../../../utils/errors';
import { logger } from '../../../utils/logger';

export class RevenueService {
  constructor(private prisma: PrismaClient) {}

  /**
   * Get total platform revenue
   */
  async totalRevenue(): Promise<number> {
    const result = await this.prisma.payment.aggregate({
      where: { status: 'COMPLETED' },
      _sum: { amount: true },
    });
    return result._sum.amount || 0;
  }

  /**
   * Get total revenue generated by a specific user (purchases made by them)
   */
  async userRevenue(userId: string): Promise<number> {
    const result = await this.prisma.payment.aggregate({
      where: { userId, status: 'COMPLETED' },
      _sum: { amount: true },
    });
    return result._sum.amount || 0;
  }

  /**
   * Get total revenue generated on a specific platform
   */
  async platformRevenue(platformId: string): Promise<number> {
    // Assuming platform ID is passed in metadata or linked via orders
    // Depending on schema, it might require a join. 
    // Fallback simple implementation:
    const platform = await this.prisma.platform.findUnique({
      where: { id: platformId },
      include: {
        courses: { select: { id: true } }
      }
    });

    if (!platform) return 0;

    // Simple sum of all course purchases on this platform
    const courseIds = platform.courses.map((c: any) => c.id);
    
    // In a real scenario, payments should be linked directly to platforms or order line items.
    return 0; // Stub: schema doesn't have direct payment->platform link
  }

  /**
   * Calculate creator earnings after platform commission
   */
  async calculateCreatorEarnings(creatorId: string): Promise<{ totalEarned: number; netProfit: number }> {
    const courses = await this.prisma.course.findMany({
      where: { instructorId: creatorId },
      select: { price: true, studentsCount: true, platform: { select: { commissionRate: true } } },
    });

    let totalEarned = 0;
    let netProfit = 0;

    for (const course of courses) {
      const gross = course.price * course.studentsCount;
      const commission = course.platform ? course.platform.commissionRate : 0.15; // default 15%
      
      totalEarned += gross;
      netProfit += gross * (1 - commission);
    }

    return { totalEarned, netProfit };
  }

  /**
   * Handle Subscription Upgrades with prorated logic
   */
  async calculateUpgradeProration(userId: string, newTierId: string): Promise<{ cost: number }> {
    // Subscription upgrade logic
    return { cost: 0 };
  }
}
